const express=require('express')
const app=express()
const env=require('./common/config/env.config')
const bodyParser=require('body-parser')
const userRoute=require('./API/users/routes.config')
const todoRoute=require('./API/Todos/routes.config')
app.use(express.json())
app.use(bodyParser.json())
//app.use()
userRoute.routeConfig(app)
app.listen(env.Port,()=>console.log('we are listening on port '+env.Port))
